name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: RuboCop
        uses: reviewdog/action-rubocop@v1
        with:
          github_token: ${{ secrets. REVIEWDOG_GITHUB_TOKEN }}

  rspec:
    runs-on: ubuntu-latest
    container: ruby:2.7.1-buster
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: vending_machine_kata_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: bundle install
      - name: Migrate database
        run: bundle exec rake db:migrate
        env:
          APP_ENV: test
          DATABASE_URL: postgres://postgres:postgres@postgres/vending_machine_kata_test
      - name: RSpec
        run: bundle exec rspec
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres/vending_machine_kata_test
          DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
